version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@sanity/cli"
    versions:
    - 2.2.3
    - 2.2.6
    - 2.3.8
    - 2.4.0
    - 2.5.0
    - 2.6.0
    - 2.7.1
    - 2.7.2
  - dependency-name: "@sanity/core"
    versions:
    - 2.2.2
    - 2.3.3
    - 2.3.8
    - 2.4.0
    - 2.6.1
    - 2.6.2
    - 2.7.0
  - dependency-name: "@sanity/default-login"
    versions:
    - 2.1.4
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
  - dependency-name: "@sanity/image-url"
    versions:
    - 0.140.19
  - dependency-name: handlebars
    versions:
    - 4.7.6
